FROM nginx:alpine

# nginx 설정 파일 복사
COPY nginx.conf /etc/nginx/nginx.conf

# SSL 디렉토리 생성
RUN mkdir -p /etc/nginx/ssl

# certbot webroot 디렉토리 생성
RUN mkdir -p /var/www/certbot

# 포트 노출
EXPOSE 80 443

# nginx 실행
CMD ["nginx", "-g", "daemon off;"]